/**
 * JWT Payload interface matching the Auth Service token structure.
 *
 * This interface represents the decoded JWT token payload that is generated
 * by the Auth Service (apps/auth/src/auth/auth.service.ts). It is used
 * throughout the Matchmaking Service to identify and authenticate users.
 *
 * @remarks
 * - The `id` field is the primary user identifier (replaces the old `sub` field)
 * - The `id` is a number as generated by the Auth Service, but should be
 *   converted to string when used with internal services (e.g., UserService)
 * - The `@JWTBody` decorator from my-fastify-decorators automatically extracts
 *   and decodes this payload from the WebSocket handshake
 *
 * @see apps/auth/src/auth/auth.service.ts - Token generation (generateTokens method)
 */
export interface JwtPayload {
	/**
	 * Unique user identifier from the Auth Service database.
	 * This is the primary key used to identify users across all services.
	 */
	id: number;

	/**
	 * User's email address.
	 * May be empty string if user registered via OAuth without email.
	 */
	email: string;

	/**
	 * User's display name / username.
	 * Empty string if user hasn't set their username yet (see noUsername flag).
	 */
	username: string;

	/**
	 * Authentication provider used for login.
	 * Possible values: 'email', 'github', 'discord', '42', etc.
	 */
	provider: string;

	/**
	 * Flag indicating the user needs to set their username.
	 * When true, the frontend should prompt the user to choose a username.
	 */
	noUsername?: boolean;

	/**
	 * Suggested username from OAuth provider (e.g., GitHub login, Discord username).
	 * Only present when noUsername is true and user logged in via OAuth.
	 */
	suggestedUsername?: string;

	/**
	 * Token issued at timestamp (Unix epoch in seconds).
	 * Standard JWT claim, automatically set by @fastify/jwt.
	 */
	iat: number;

	/**
	 * Token expiration timestamp (Unix epoch in seconds).
	 * Standard JWT claim, automatically set by @fastify/jwt.
	 */
	exp: number;
}

/**
 * Représente un joueur actuellement en attente dans la file de matchmaking.
 * Cet objet agit comme un instantané (snapshot) des données nécessaires à l'algorithme.
 */
export interface QueuedPlayer {
	/** Identifiant unique du joueur (Clé primaire métier) */
	userId: string;

	/** Identifiant technique de la connexion WebSocket */
	socketId: string;

	/** Score ELO figé au moment de l'inscription */
	elo: number;

	/** Timestamp (ms) de l'entrée dans la file (référence pour l'attente) */
	joinTime: number;

	/** Multiplicateur dynamique de tolérance (défaut: 1) */
	rangeFactor: number;

	/**
	 * Indique si le joueur est prioritaire.
	 * True si le joueur revient dans la file après qu'un adversaire a refusé un match.
	 */
	priority: boolean;
}

/**
 * États possibles de la réponse d'un joueur à une proposition de match.
 */
export type MatchResponseStatus = 'PENDING' | 'ACCEPTED' | 'DECLINED';

/**
 * Représente un match proposé mais pas encore validé par les deux parties.
 */
export interface PendingMatch {
	matchId: string;
	player1: {
		userId: string;
		socketId: string;
		elo: number;
		status: MatchResponseStatus;
	};
	player2: {
		userId: string;
		socketId: string;
		elo: number;
		status: MatchResponseStatus;
	};
	/** Date d'expiration de la proposition (Timestamp ms) */
	expiresAt: number;
	/** Référence au timer Node.js pour pouvoir l'annuler si tout le monde répond avant */
	timeoutId?: NodeJS.Timeout;
}

/**
 * Factory function pour instancier un QueuedPlayer avec des valeurs par défaut sécurisées.
 * Inclut un log de debug verveux pour tracer la création de l'objet.
 *
 * @param userId - L'UUID de l'utilisateur
 * @param socketId - L'ID du socket client
 * @param elo - Le score ELO actuel
 * @param priority - (Optionnel) Si le joueur doit être traité en priorité
 */
export function createQueuedPlayer(
	userId: string,
	socketId: string,
	elo: number,
	priority: boolean = false,
): QueuedPlayer {
	const joinTime = Date.now();
	const rangeFactor = 1;

	const player: QueuedPlayer = {
		userId,
		socketId,
		elo,
		joinTime,
		rangeFactor,
		priority,
	};

	return player;
}
